# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
  paths:
    exclude:
      - '**/build-*.yml'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore BlazorGrid.Demo'
  inputs:
    command: restore
    projects: 'BlazorGrid.Demo/BlazorGrid.Demo.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Restore BlazorGrid.Demo.Tests'
  inputs:
    command: restore
    projects: 'BlazorGrid.Demo.Tests/BlazorGrid.Demo.Tests.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build BlazorGrid.Demo'
  inputs:
    command: build
    projects: 'BlazorGrid.Demo/BlazorGrid.Demo.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'BlazorGrid.Demo.Tests/BlazorGrid.Demo.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    zipAfterPublish: false
    projects: 'BlazorGrid.Demo/BlazorGrid.Demo.csproj'
    arguments: '-c $(Build.Configuration) -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'