# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
  paths:
    exclude:
      - '**/build-*.yml'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm restore'
  inputs:
    command: 'install'
    workingDir: 'BlazorGrid'

- task: gulp@1
  displayName: 'gulp default'
  inputs:
    gulpFile: 'BlazorGrid/gulpfile.js'
    targets: 'default'

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore BlazorGrid'
  inputs:
    command: restore
    projects: 'BlazorGrid/BlazorGrid.csproj'
    arguments: '/Property:Configuration=$(buildConfiguration)'
    verbosityRestore: Normal

- task: DotNetCoreCLI@2
  displayName: 'Restore BlazorGrid.Tests'
  inputs:
    command: restore
    projects: 'BlazorGrid.Tests/BlazorGrid.Tests.csproj'
    arguments: '/Property:Configuration=$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build BlazorGrid'
  inputs:
    command: 'build'
    projects: 'BlazorGrid/BlazorGrid.csproj'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'BlazorGrid.Tests/BlazorGrid.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'