# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
  paths:
    exclude:
      - '**/build-*.yml'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: 'Build BlazorGrid.Demo'
  inputs:
    command: build
    configuration: $(buildConfiguration)
    projects: 'BlazorGrid.Demo/BlazorGrid.Demo.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    configuration: $(buildConfiguration)
    projects: 'BlazorGrid.Demo.Tests/BlazorGrid.Demo.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    zipAfterPublish: false
    configuration: $(buildConfiguration)
    projects: 'BlazorGrid.Demo/BlazorGrid.Demo.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'