name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build BlazorGrid --configuration Release --no-restore
      
    - name: Test
      run: dotnet test BlazorGrid.Tests --no-restore --verbosity normal

    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.4.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: 'BlazorGrid/bin/Release/netstandard2.1'
